# Utilisez une image de Node.js comme image de base
FROM node:latest as production

# Définissez le répertoire de travail pour l'application
WORKDIR /app

# Copiez les fichiers package.json et package-lock.json dans le répertoire de travail
COPY package*.json ./

# Installez les dépendances de l'application
RUN npm install

# Copiez le reste des fichiers de l'application dans le répertoire de travail
COPY . .

# Exposez le port 3000 pour l'application
EXPOSE 3000

# Démarrez l'application
CMD ["node", "server.js"]
